/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import jdbc.DatabaseInitService;
import jdbc.DatabasePopulateService;
import jdbc.DatabaseQueryService;
import model.ProjectPrices;

import java.io.IOException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException, SQLException {
////        метод для створення таблиць
//        new DatabaseInitService().createTableFromFile();
//        new DatabaseInitService().dropTable();



//        //методи для заповнення таблиці
//        System.out.println("Кількість працівників: ");
//        new DatabasePopulateService().addWorker(1);
//        System.out.println("Кількість проектів: ");
//        new DatabasePopulateService().addProject(1);
//        System.out.println("Кількість записів, що поєднує працівника з проектом: ");
//        new DatabasePopulateService().addProjectsWorker(1);
//        System.out.println("Кількість клієнтів: ");
//        System.out.println(Arrays.toString(new DatabasePopulateService().addClient(1)));

//        //методи для заповнення таблиці з sql файлу
//        new DatabasePopulateService().addWorkerFromFile();
//        new DatabasePopulateService().addClientFromFile();
//        new DatabasePopulateService().addProjectFromFile();
//        new DatabasePopulateService().addProjectsWorkerFromFile();




        //методи для виконання select-запитів з sql файлів

        for (Object o:new DatabaseQueryService().printProjectPrices()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:new DatabaseQueryService().findMaxSalaryWorker()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:new DatabaseQueryService().findYoungestEldestWorkers()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:new DatabaseQueryService().findLongestProject()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:new DatabaseQueryService().findMaxProjectsClient()) {
            System.out.println(o);
        }
        System.out.println();
    }
}
